# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4f6f466b-aae0-4892-bf36-bf3b7a4d0f0a";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-5db8742d-d7f2-4060-ab30-a0c2f395192b".device = "/dev/disk/by-uuid/5db8742d-d7f2-4060-ab30-a0c2f395192b";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/257F-0016";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/385c3dfa-51b0-4f37-8752-0f0a14a30c3a"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
